version: 2
builds:
- id: "kagenti-operator"
  dir: kagenti-operator
  main: ./cmd
  binary: ./bin/kagenti-operator-manager
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm64
  ignore:
  - goos: darwin
    goarch: ppc64le
  env:
  - CGO_ENABLED=0

archives:
- ids: [kagenti-operator]

kos:
  - id: "kagenti-operator-ko"
    repositories:
    - ghcr.io/kagenti/kagenti-operator/kagenti-operator
    working_dir: kagenti-operator
    main: ./cmd
    build: kagenti-operator
    tags:
      - '{{.Version}}'
      - latest
    bare: true
    preserve_import_paths: false
    platforms:
      - linux/amd64
      - linux/arm64
    env:
      - CGO_ENABLED=0
release:
  draft: false
  prerelease: auto
  mode: keep-existing
